## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

#### 2.1 Series와 DataFrame
Series

In [1]:
import pandas as pd

In [ ]:
scores = pd.Series([90, 85, 88])
print(scores)

# index value
#   0    90
#   1    85
#   2    88
# dtype: int64

0    90
1    85
2    88
dtype: int64

DataFrame

In [ ]:
data = {
    '이름' : ['김철수', '이영희', '박민수'],
    '부서' : ['개발', '기획', '개발'],
    '급여' : [4500, 5200, 4800]
}

df = pd.DataFrame(data)
print(df)
#     이름  부서    급여
# 0  김철수  개발  4500
# 1  이영희  기획  5200
# 2  박민수  개발  4800

    이름  부서    급여
0  김철수  개발  4500
1  이영희  기획  5200
2  박민수  개발  4800

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

In [10]:
print(f'df.info : {df.info()}')
print(f'df.decribe : {df.describe()}' )

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   부서      3 non-null      str
 2   급여      3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes
df.info : None
df.decribe :                 급여
count     3.000000
mean   4833.333333
std     351.188458
min    4500.000000
25%    4650.000000
50%    4800.000000
75%    5000.000000
max    5200.000000

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [ ]:
df['보너스'] = df['급여'] * 0.1
print(df)
#     이름  부서   급여   보너스
# 0  김철수  개발  4500  450.0
# 1  이영희  기획  5200  520.0
# 2  박민수  개발  4800  480.0

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

In [ ]:
# 인덱스 특정 컬럽으로 변경하기
df_indexed = df.set_index('이름')
print(df_indexed)
#       부서   급여   보너스
# 이름                  
# 김철수  개발  4500  450.0
# 이영희  기획  5200  520.0
# 박민수  개발  4800  480.0

     부서    급여    보너스
이름
김철수  개발  4500  450.0
이영희  기획  5200  520.0
박민수  개발  4800  480.0

In [ ]:
# 인덱스를 다시 숫자형 인덱스로 변경하기
df_restored = df_indexed.reset_index()

print(df_restored)
#     이름  부서   급여   보너스
# 0  김철수  개발  4500  450.0
# 1  이영희  기획  5200  520.0
# 2  박민수  개발  4800  480.0

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

In [ ]:
df = pd.DataFrame({
    '중간고사' : [80, 95, 70],
    '기말고사' : [85, 90, 75]
}, index=['김철수', '이영희', '박민수']) 

print(df)
#      중간고사  기말고사
# 김철수    80    85
# 이영희    95    90
# 박민수    70    75

     중간고사  기말고사
김철수    80    85
이영희    95    90
박민수    70    75

In [ ]:
score_means = df.mean(axis=0) # 행 기준 ( 인덱스 기준 )
print(score_means)

# 중간고사    81.666667
# 기말고사    83.333333
# dtype: float64ㅠ

중간고사    81.666667
기말고사    83.333333
dtype: float64

In [ ]:
score_gap = df.sub(score_means, axis=1)
print(score_gap)
#          중간고사    기말고사
# 김철수  -1.666667  1.666667
# 이영희  13.333333  6.666667
# 박민수 -11.666667 -8.333333

          중간고사      기말고사
김철수  -1.666667  1.666667
이영희  13.333333  6.666667
박민수 -11.666667 -8.333333

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택

In [2]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "나이" : [25, 30, 35, 40],
    "점수" : [80, 95, 70, 85],
    "등급" : ['B', 'A', 'C', 'D']
}, index=['user1', 'user2', 'user3', 'user4'])

In [14]:
print(df.loc['user1'])
# 나이    25
# 점수    80
# 등급     B
# Name: user1, dtype: object
print(df.loc['user1', '등급']) # B

df.loc['user1' : 'user3' , ['점수', '등급']]
# 	   점수	등급
# user1	80	B
# user2	95	A
# user3	70	C

나이    25
점수    80
등급     B
Name: user1, dtype: object
80

In [17]:

df.loc['user1' : 'user3' , ['점수', '등급']]
# 	   점수	등급
# user1	80	B
# user2	95	A
# user3	70	C

       점수 등급
user1  80  B
user2  95  A
user3  70  C

In [18]:
print(df.loc['user1':'user2', '점수':'등급'])
#        점수 등급
# user1  80  B
# user2  95  A

       점수 등급
user1  80  B
user2  95  A

In [20]:
print(df.iloc[0:2, 1:3])
#        점수 등급
# user1  80  B
# user2  95  A₩

       점수 등급
user1  80  B
user2  95  A

#### 3.2 불리언 인덱싱과 query() 조건 검색

불리언 인덱싱

In [21]:
df['나이'] >= 30

user1    False
user2     True
user3     True
user4     True
Name: 나이, dtype: bool

In [29]:
bdf[(df['나이'] < 30) | (df['등급'] > 'D')]

       나이  점수 등급
user1  25  80  B

In [ ]:
df.query('나이 >= 30 and 점수 >= 80')

query() 필터링

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)

In [31]:
import numpy as np
# 결측치 - np.nan, pd.NA, NONE
raw_df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [pd.NA, 5, 6], 'C': [7, 8, 9]})

In [37]:
raw_df.isnull().sum()
# A    1
# B    1
# C    0
# dtype: int64

A    1
B    1
C    0
dtype: int64

3.3.2 결측치 삭제 (Drop)

In [34]:
raw_df.dropna(axis=1)

   C
0  7
1  8
2  9

3.3.3 통계적 대푯값 대치 (Imputation)

In [38]:
df_age = pd.DataFrame({'나이': [20, 25, None, 30, 95]})

In [43]:
median_val = df_age['나이'].median()
df_age['나이'] = df_age['나이'].fillna(median_val)
print(df_age)

#    나이
# 0  20.0
# 1  25.0
# 2  27.5
# 3  30.0
# 4  95.0

     나이
0  20.0
1  25.0
2  27.5
3  30.0
4  95.0

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)

In [45]:
ts_df = pd.DataFrame({'온도': [18.2, None, None, 21.0]})

# ffill
ts_df.ffill()
#   온도
# 0	18.2
# 1	18.2
# 2	18.2
# 3	21.0

# bfill
ts_df.bfill()
#    온도
# 0	18.2
# 1	21.0
# 2	21.0
# 3	21.0

     온도
0  18.2
1  21.0
2  21.0
3  21.0

3.3.5 선형 보간법 (Linear Interpolation)

In [46]:
speed_df = pd.DataFrame({'속도': [10.0, None, None, 40.0]})

speed_df['속도'] = speed_df['속도'].interpolate(method='linear')
print(speed_df)
#     속도
# 0  10.0
# 1  20.0
# 2  30.0
# 3  40.0

     속도
0  10.0
1  20.0
2  30.0
3  40.0

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)

In [47]:
survey_df = pd.DataFrame({'점수': [85, -999, '?', 95]})

survey_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   점수      4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [48]:
survey_df.describe()

        점수
count    4
unique   4
top     85
freq     1

In [50]:
survey_df['점수'] = survey_df['점수'].replace([-999, '?'], pd.NA)
print(survey_df)
#      점수
# 0    85
# 1   <NA>
# 2   <NA>
# 3    95

     점수
0    85
1  <NA>
2  <NA>
3    95

In [54]:
survey_df['점수'] = survey_df['점수'].replace([-999, '?'], pd.NA)
print(survey_df) # type이 object여서 통계 확인 불가능
#      점수
# 0    85
# 1   <NA>
# 2   <NA>
# 3    95

survey_df['점수'] = pd.to_numeric(survey_df['점수'], errors='coerce')
survey_df.describe() # to_numeric으로 type을 실수로 변경하여 통계 확인 가능

# 점수
# count	2.000000
# mean	90.000000
# std	7.071068
# min	85.000000
# 25%	87.500000
# 50%	90.000000
# 75%	92.500000
# max	95.000000

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   점수      2 non-null      float64
dtypes: float64(1)
memory usage: 164.0 bytes

In [55]:
survey_df.describe()

              점수
count   2.000000
mean   90.000000
std     7.071068
min    85.000000
25%    87.500000
50%    90.000000
75%    92.500000
max    95.000000

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)

In [56]:
user_df = pd.DataFrame({'소득': [300, None, 450, None]})

In [57]:
user_df['응답여부'] = user_df['소득'].isna()

print(user_df)
#     소득   응답여부
# 0  300.0  False
# 1    NaN   True
# 2  450.0  False
# 3    NaN   True

      소득   응답여부
0  300.0  False
1    NaN   True
2  450.0  False
3    NaN   True

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환

In [58]:
sales_df = pd.DataFrame({'지점': ['서울', '서울', '부산', '부산'], '매출': [100, 150, 80, 120]})

In [68]:
sales_df = pd.DataFrame({'지점': ['서울', '서울', '부산', '부산'], '매출': [100, 150, 80, 120]})
grouped_df = sales_df.groupby('지점').mean(numeric_only=True) # 숫자 아닌 데이터가 있을 경우 숫자만 골라서 연산함
print(grouped_df)
#       매출
# 지점       
# 부산  100.0
# 서울  125.0

sales_df['매출'].to_numpy(dtype=np.float64)
# array([100., 150.,  80., 120.])

       매출
지점
부산  100.0
서울  125.0

In [69]:
sales_df['매출'].to_numpy(dtype=np.float64)
# array([100., 150.,  80., 120.])

array([100., 150.,  80., 120.])